export const ERROR_CODES = {
  // Validation Errors (400)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PAYMENT_DATA: "INVALID_PAYMENT_DATA",
  INVALID_WEBHOOK_DATA: "INVALID_WEBHOOK_DATA",

  // Payment Errors (400)
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",
  INVALID_PAYMENT_METHOD: "INVALID_PAYMENT_METHOD",
  INSUFFICIENT_AMOUNT: "INSUFFICIENT_AMOUNT",
  AMOUNT_TOO_HIGH: "AMOUNT_TOO_HIGH",

  // Integration Errors (500)
  MERCADOPAGO_API_ERROR: "MERCADOPAGO_API_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",

  // System Errors (500)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
